### ISSUE TITLE
high power RBAC configuration

### ISSUE THREAD

**Issue by kanatohodets** [Datera/datera-csi#5]
Hi!

I'm looking at the RBAC configuration, and it has a couple of powers which I'm not sure I understand:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-datera-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
   # snip
```
and
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-datera-snapshotter-role
rules:
   # snip
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
```

This means that these two components are able to read any Secret object in the cluster. By extension, that means they can read any Service Account Token or Certificate and assume the identity/powers of any service account in the cluster.

Is this amount of power required for the Datera provisioner and snapshotter to work, or do they really just need access to one particular set of Secret objects - for example, in a single namespace? None of the RBAC configuration specifies the creation of Secret objects, so it doesn't seem likely that there are lots of dynamically created Secrets all over the cluster that the automation needs to consume.

Thanks!

**Comment by kanatohodets** [comment]
Looking into this topic a bit more, I can see that this is basically the suggested approach for CSI provisioners and snapshotters, based on the [reference](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml#L19) [implementations](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml#L29) and the [docs](https://kubernetes-csi.github.io/docs/secrets-and-credentials.html).

Scanning the [StorageClass](https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html) and [VolumeSnapshotClass](https://kubernetes-csi.github.io/docs/secrets-and-credentials-volume-snapshot-class.html) docs, I think I can avoid granting cluster-wide Secret access by ensuring that all StorageClass and VolumeSnapshotClass objects always refer to secrets located in a single namespace, and granting the snapshotter/provisioner service account a namespace-scoped Role/RoleBinding to read those secrets.

Does that sound about right, or is there another motivation for cluster-wide Secret access that I'm missing?

Thanks!

**Comment by virgilm** [comment]
Ben, that sounds about right, you should be able to restrict access to a single namespace, like "pd-ssd-credentials" in the link you mentioned.

Our example does not seem to have it, but you should be able to use something like:

```
kind: StorageClass
[...]
parameters:
  csi.storage.k8s.io/provisioner-secret-name: fast-storage-provision-key
  csi.storage.k8s.io/provisioner-secret-namespace: pd-ssd-credential

```
